# Generated by Django 5.2.8 on 2025-12-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocalificacion',
            old_name='Trabajo',
            new_name='Actividad',
        ),
    ]
